services:
  e-commerce-tg-bot:
    build:
      context: .
      dockerfile: docker/e-commerce-tg-bot/Dockerfile
      target: local
      args:
        PROJECT_DIR: ${PROJECT_DIR:-/app}
    container_name: e-commerce-tg-bot
    env_file:
      - .env
    restart: always
    depends_on:
      - tg_postgres

  tg_postgres:
    image: postgres:16
    container_name: tg_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tg_db}
      PGUSER: ${POSTGRES_USER:-postgres}
      PGDATABASE: ${POSTGRES_DB:-tg_db}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "telegram_bot_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - tg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


volumes:
  tg-data: { }