"""update users

Revision ID: ca0f28a1a234
Revises: 07998c4a4841
Create Date: 2025-10-05 16:41:58.934097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0f28a1a234'
down_revision: Union[str, Sequence[str], None] = '07998c4a4841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('uq_tg_id_tg_username'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_tg_id_tg_username'), 'users', ['tg_id', 'tg_username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'tg_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
